apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  namespace: sirius
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app
          image: mokhnatkinayana/api-app:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "400m"
          envFrom:
            - configMapRef:
                name: api-conf